### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by kartheekmedathati** [tanglang96/DataLoaders_DALI#27]
Traceback (most recent call last):
  File "cifar10.py", line 166, in <module>
    images = data[0].cuda(non_blocking=True)
AttributeError: 'dict' object has no attribute 'cuda'

**Comment by nlp-tokio** [comment]
images = data[0]["data"].cuda(non_blocking=True)
targets = data[0]["label"].cuda(non_blocking=True) is okay for me.

**Comment by nlp-tokio** [comment]
> Traceback (most recent call last):
> File "cifar10.py", line 166, in
> images = data[0].cuda(non_blocking=True)
> AttributeError: 'dict' object has no attribute 'cuda'

images = data[0]["data"].cuda(non_blocking=True)
targets = data[0]["label"].cuda(non_blocking=True) is okay for me.

**Comment by minh-h-ng** [comment]
I encountered the same problem; it turns out that the implementation of DALIDataloader in base.py returns the first batch in different format than the subsequent ones. So you need to update as follows:

```
def __next__(self):
        if self._first_batch is not None:
            batch = self._first_batch[0]
            self._first_batch = None
            if self.onehot_label:
                return [batch[self.output_map[0]], batch[self.output_map[1]].squeeze().long()]
            else:
                return [batch[self.output_map[0]], batch[self.output_map[1]]]
        data = super().__next__()[0]
        if self.onehot_label:
            return [data[self.output_map[0]], data[self.output_map[1]].squeeze().long()]
        else:
            return [data[self.output_map[0]], data[self.output_map[1]]]
```
